# Generated by Django 3.1.5 on 2021-01-04 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'verbose_name': 'Car', 'verbose_name_plural': 'Cars'},
        ),
    ]
